CREATE TABLE Staff (
    StaffID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Staffname VARCHAR(50) NOT NULL,
    Staffposition VARCHAR(50) NOT NULL,
    Staffphone INT NOT NULL,
    Staffadd VARCHAR(50) NOT NULL,
    Staffemail VARCHAR(50) NOT NULL,
    Password VARCHAR(6) NOT NULL,
    Username VARCHAR(50) NOT NULL
);

CREATE TABLE CustomerSender (
    CustSID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Custname VARCHAR(50) NOT NULL,
    Custphone INT NOT NULL,
    Custadd VARCHAR(50) NOT NULL,
    Custposcode INT NOT NULL,
    Custemail VARCHAR(50) NOT NULL
);

CREATE TABLE CustomerReceiver (
    CustRID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Custname VARCHAR(50) NOT NULL,
    Custphone INT NOT NULL,
    Custadd VARCHAR(50) NOT NULL,
    Custposcode INT NOT NULL,
    Custemail VARCHAR(50) NOT NULL
);

CREATE TABLE Item (
    ItemID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Weight DECIMAL,
    Height DECIMAL,
    Fee DECIMAL,
    Shiptype VARCHAR(100) UNIQUE NOT NULL,
    StaffID INT NOT NULL,
    CustRID INT NOT NULL,
    CustSID INT NOT NULL,
    CONSTRAINT FK_StaffItem FOREIGN KEY (StaffID)
    REFERENCES Staff(StaffID),
    CONSTRAINT FK_CustomerReceiverItem FOREIGN KEY (CustRID)
    REFERENCES CustomerReceiver(CustRID),
    CONSTRAINT FK_CustomerSenderItem FOREIGN KEY (CustSID)
    REFERENCES CustomerSender(CustSID)
);

CREATE TABLE Branch (
    BranchID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Location VARCHAR(50) NOT NULL,
    Poscode VARCHAR(50) NOT NULL
);

CREATE TABLE Vehicle (
    VehicleID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Type VARCHAR(50) NOT NULL,
    NoPlate VARCHAR(50) NOT NULL
);

CREATE TABLE Item_Branch (
    IBID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DateTime DATE,
    Status VARCHAR(50),
    ItemID INT NOT NULL,
    BranchID INT NOT NULL,
    VehicleID INT NOT NULL,
    CONSTRAINT FK_BranchItem FOREIGN KEY (ItemID)
    REFERENCES Item(ItemID),
    CONSTRAINT FK_ItemBranch FOREIGN KEY (BranchID)
    REFERENCES Branch(BranchID),
    CONSTRAINT FK_ItemBranchVehicle FOREIGN KEY (VehicleID)
    REFERENCES Vehicle(VehicleID)
);